version: "3.5"

networks:
  data:
    driver: bridge

services:
  vm:
    image: victoriametrics/victoria-metrics:latest
    container_name: vm
    hostname: vm
    restart: always
    stop_grace_period: 5m
    networks:
      - data
    ports:
      - 8428:8428/tcp
    volumes:
      - ./data/vm:/data
    command:
      - "-storageDataPath=/data"
      - "-loggerLevel=INFO"
      - "-loggerFormat=default"
      - "-httpListenAddr=:8428"
      - "-retentionPeriod=24"
      - "-memory.allowedPercent=60"
      - "-influxSkipSingleField"
      - "-selfScrapeInterval=30s"
  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    hostname: loki
    restart: always
    stop_grace_period: 5m
    networks:
      - data
    ports:
      - 3100:3100/tcp
    volumes:
      - ./cfg/loki.yml:/etc/loki/local-config.yaml
      - ./data/loki:/data
    command:
      - "-config.file=/etc/loki/local-config.yaml"
      - "-log.level=info"
      - "-log.format=logfmt"
    security_opt:
      - seccomp:unconfined
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    networks:
      - data
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=flant-statusmap-panel
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./cfg/grafana/provisioning/:/etc/grafana/provisioning/
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - vm
      - loki
